version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: dianhsu
      RABBITMQ_DEFAULT_PASS: dianbot
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: dianhsu
      POSTGRES_PASSWORD: dianbot
      POSTGRES_DB: bot
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379