
name: Release - dianbot

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.11'

      - name: Install require python modules
        run: |
          pip install requests

      - name: Send update information
        run: |
          version="${{ github.ref }}"
          content="`git log -1 --format=%B`"
          commit_hash="`git log -1 --format=%H`"
          python ./tool/announcement.py "${{ github.ref }}" "$content" "$commit_hash" "${{ secrets.BOT_TOKEN }}" "${{ secrets.CHANNEL_ID }}"
